
ALL_LANGUAGES = "ar tr zh el es en sw hi mr ur ta te th ru bg he ka vi fr de".split()  # 20 langs from own previous work
MASSIVE_LANG_MAP = {"en": "en-US",
                    "af": "af-ZA",
                    "am": "am-ET",
                    "ar": "ar-SA",
                    "az": "az-AZ",
                    "bn": "bn-BD",
                    "cy": "cy-GB",
                    "da": "da-DK",
                    "de": "de-DE",
                    "el": "el-GR",
                    "es": "es-ES",
                    "fa": "fa-IR",
                    "fi": "fi-FI",
                    "fr": "fr-FR",
                    "id": "id-ID",
                    "he": "he-IL",
                    "hi": "hi-IN",
                    "hu": "hu-HU",
                    "hy": "hy-AM",
                    "is": "is-IS",
                    "it": "it-IT",
                    "ja": "ja-JP",
                    "jv": "jv-ID",
                    "ka": "ka-GE",
                    "km": "km-KH",
                    "kn": "kn-IN",
                    "ko": "ko-KR",
                    "lv": "lv-LV",
                    "ml": "ml-IN",
                    "mn": "mn-MN",
                    "pl": "pl-PL",
                    "pt": "pt-PT",
                    "ru": "ru-RU",
                    "sw": "sw-KE",
                    "th": "th-TH",
                    "tl": "tl-PH",
                    "tr": "tr-TR",
                    "ur": "ur-PK",
                    "zh": "zh-CN",
                    }  # 35 langs from Liu & Niehues
ALL_LANGUAGES.extend(MASSIVE_LANG_MAP.keys())
ALL_LANGUAGES = list(set(ALL_LANGUAGES))  # union

SENT_SUMM_TEMPLATE = "This sentence: {sent} means in one word:"
